sonar.projectKey=0c8aad126287db9b7f9e94e37121138c8dee8f01
sonar.organization=8.2CDevSecOps
sonar.host.url=https://sonarcloud.io
sonar.login=${SONAR_TOKEN}
sonar.sources=.
sonar.exclusions=node_modules/**
